apiVersion: adaptdl.petuum.com/v1
kind: AdaptDLJob
metadata:
  generateName: imagenet-
spec:
        # placement: ["phodgx2", "phodgx2", "phodgx2", "phodgx2"]
  template:
    spec:
      hostIPC: true
      #tolerations:
      #- key: "experiment-reserved"
      #  operator: "Equal"
      #  value: "suhasj"
      #  effect: "NoSchedule"
        #      hostNetwork: true
      containers:
      - name: main
        securityContext:
          capabilities:
            add: ["IPC_LOCK"]
        command:
        - python3
        - /root/imagenet/main.py
        - --arch=resnet50
        - --batch-size=200
        - --lr=0.08
        - --epochs=90
        - --autoscale-bsz
        - /pollux/imagenet
        env:
        - name: PYTHONUNBUFFERED
          value: "true"
        - name: NCCL_DEBUG
          value: "INFO"

        resources:
          limits:
            nvidia.com/gpu: 1
            rdma/hca: 0
            cpu: 9
            memory: "40G"
          requests:
            nvidia.com/gpu: 1
            rdma/hca: 0
            cpu: 9
            memory: "40G"
        volumeMounts:
        - name: data
          mountPath: /mnt
          readOnly: true
      volumes:
      - name: data
        hostPath:
          path: /mnt
          type: Directory
      imagePullSecrets:
      - name: regcred
