apiVersion: adaptdl.petuum.com/v1
kind: AdaptDLJob
metadata:
  generateName: yolov3-
spec:
        # placement: ["phodgx1", "phodgx1"]
  template:
    spec:
            #      hostNetwork: true
      hostIPC: true
      #tolerations:
      #- key: "experiment-reserved"
      #  operator: "Equal"
      #  value: "suhasj"
      #  effect: "NoSchedule"
      containers:
      - name: main
        securityContext:
          capabilities:
            add: ["IPC_LOCK"]
        command:
        - python3
        - /root/yolov3/train.py
        - --weight_path=/mnt/darknet53_448.weights
        env:
        - name: NCCL_DEBUG
          value: "INFO"
        - name: PYTHONUNBUFFERED
          value: "true"
        resources:
          limits:
            nvidia.com/gpu: 1
            rdma/hca: 0
            cpu: 9
            memory: "40G"
          requests:
            nvidia.com/gpu: 1
            rdma/hca: 0
            cpu: 9
            memory: "40G"
        volumeMounts:
        - name: data
          mountPath: /mnt
          readOnly: true
      volumes:
      - name: data
        hostPath:
          path: /mnt
          type: Directory
      imagePullSecrets:
      - name: regcred
