apiVersion: adaptdl.petuum.com/v1
kind: AdaptDLJob
metadata:
  generateName: ncf-
spec:
        # placement: ["phodgx1"]
  maxReplicas: 1
  template:
    spec:
            #      hostNetwork: true
            #tolerations:
            #- key: "experiment-reserved"
            #operator: "Equal"
            #value: "suhasj"
            #effect: "NoSchedule"
      hostIPC: true
      containers:
      - name: main
        securityContext:
          capabilities:
            add: ["IPC_LOCK"]
        command:
        - python3
        - /root/ncf/main.py
        - --epochs=10
        env:
        - name: PYTHONUNBUFFERED
          value: "true"
        - name: TARGET_BATCH_SIZE
          value: "32768"
        resources:
          limits:
            nvidia.com/gpu: 1
            rdma/hca: 0
            cpu: 9
            memory: "40G"
          requests:
            nvidia.com/gpu: 1
            rdma/hca: 0
            cpu: 9
            memory: "40G"
        volumeMounts:
        - name: data
          mountPath: /mnt
          readOnly: true
      volumes:
      - name: data
        hostPath:
          path: /mnt
          type: Directory
      imagePullSecrets:
      - name: regcred
